name: Download Artifact
description: Download build files

inputs:
  name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Download
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.name }}
