

name: CD - Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download All Artifacts
        uses: ./.github/actions/Download_Artifact

      - name: Show Files
        run: ls -R
