name: CD - Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    #  - name: Checkout Repository
        #uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: Jijo2403Organization/GitHub_Task2/.github/actions/Download_Artifact@main
      - name: Show Files
        run: ls -R
