name: Deploy

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  deploy:
    runs-on:
      group: Demo runner group   
      labels: [self-hosted, Windows, X64, github]  

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: publish
      - run: echo ${{ inputs.name }}

      - run: |
          powershell -Command "Remove-Item 'D:\github artifact repo\*' -Recurse -Force -ErrorAction SilentlyContinue"
          powershell -Command "Copy-Item 'publish\*' 'D:\github artifact repo\' -Recurse -Force"
